feat: initial data processing
seedcase-project/examples pull request #14
Opened 2024-12-20 08:58 UTC by K-Beicher

## Description

This PR collects some scripts which is used to process the male seed beetle dataset. 

The check for lost values during import is helped by Polars throwing a hissy fit if there are char further down in columns that it believes are int or float, which means that for this data set it makes sense to check the fields that polars have decided are strings for numerical values. Having said that, there must be a more elegant way to check for it, so this will need some more work.

Closes #11 

This PR needs an in-depth review.

## Checklist

- [ ] Ran spell-check
- [ ] Formatted Markdown

2024-12-20 12:40 UTC, lwjohnst86 commented on male-seed-beetle/scripts/convert-with-core.py
> +Path('../data-raw/data1.csv').rename('../data-raw/data.csv')
This can actually be removed and keep both processed and the original, so you can always rerun this script without downloading the data again.

2025-01-03 10:38 UTC, lwjohnst86 requested changes

2025-01-03 10:38 UTC, lwjohnst86 commented on male-seed-beetle/scripts/convert-with-core.py
> +            csv.write(content)
Include option to overwrite if it isn't already the default.

2025-01-03 10:38 UTC, lwjohnst86 commented on male-seed-beetle/scripts/convert-with-core.py
> +df.write_csv('../data-raw/data.csv')
```suggestion
```

Writing only needs to happen at the end of the script

2025-01-03 10:38 UTC, lwjohnst86 commented on male-seed-beetle/scripts/convert-with-core.py
> +df.write_csv('../data-raw/data.csv')
```suggestion
```

2025-01-03 10:38 UTC, lwjohnst86 commented on male-seed-beetle/scripts/convert-with-core.py
> +                #TODO Need to rework this bit
This could be converted more simply (though manually) by using `polars.glimpse()`.

2025-01-03 10:38 UTC, lwjohnst86 commented on male-seed-beetle/scripts/convert-with-core.py
> +#df = pl.read_csv('../data-raw/data.csv')
```suggestion
```

2025-01-03 10:38 UTC, lwjohnst86 commented on male-seed-beetle/scripts/convert-with-core.py
> +df = df.rename(column_names)
This could be moved to the top as one of the first processing steps.

2025-01-03 10:38 UTC, lwjohnst86 commented on male-seed-beetle/scripts/convert-with-core.py
> +)
```suggestion
df = df.rename({col: col.lower() for col in df.columns})
    .with_columns(
        block=pl.col("block").replace_strict(block_mapping, return_dtype=pl.Utf8),
        treatment=pl.col("treatment").replace_strict(treatment_map),
    )
```

I think something like this will work, called method chaining.

Plus you can modify or add multiple columns within `with_columns()`.

2025-01-03 13:12 UTC, K-Beicher commented on male-seed-beetle/scripts/convert-with-core.py
> +            csv.write(content)
It'll run multiple times in a row, so it looks like it is default behaviour.

2025-01-06 13:13 UTC, lwjohnst86 requested changes
Just some more comments :relaxed:

2025-01-06 13:13 UTC, lwjohnst86 commented on male-seed-beetle/scripts/convert-with-core.py
> +            csv.write(content)
Remove these empty lines above, they aren't necessary and make the code a bit harder to read :relaxed:

2025-01-06 13:13 UTC, lwjohnst86 commented on male-seed-beetle/scripts/convert-with-core.py
> +    with open('../data-raw/data1.csv', 'w') as csv:
```suggestion
    with open('../data-raw/data-ready.csv', 'w') as csv:
```

Or some other name to indicate the status/content of the new data file.

2025-01-06 13:17 UTC, K-Beicher commented on male-seed-beetle/scripts/convert-with-core.py
> +    with open('../data-raw/data1.csv', 'w') as csv:
We did talk about that!

2025-01-06 14:02 UTC, lwjohnst86 approved these changes
Coooollll :star:

2025-01-06 14:03 UTC, merged